# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Plugins
plugins=(git macos aliases colorize)

source $ZSH/oh-my-zsh.sh

# User configuration

#### Aliass
alias zshconfig="vi ~/.zshrc"

# CotEditor CLI
if [[ -x /Applications/CotEditor.app/Contents/SharedSupport/bin/cot ]]; then
  alias cot='/Applications/CotEditor.app/Contents/SharedSupport/bin/cot'
elif [[ -x ~/Applications/CotEditor.app/Contents/SharedSupport/bin/cot ]]; then
  alias cot='~/Applications/CotEditor.app/Contents/SharedSupport/bin/cot'
fi

# Random String
alias random_string="cat /dev/urandom | base64 | tr -dc '0-9a-zA-Z' | head -c100"

#### SDK MAN -> Java
export SDKMAN_DIR="$HOME/.sdkman"
#[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
alias sdk='[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk'

#### NodeJS packages
export NVM_DIR="$HOME/.nvm"
alias nvm='[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm'
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Load Angular CLI autocompletion.
#source <(ng completion script)

#### PyEnv
export PYENV_ROOT="$HOME/.pyenv"
#[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init - zsh)"
alias pyenv='
  if [[ -z "$__PYENV_INITIALIZED" ]]; then
    [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init - zsh)"
    export __PYENV_INITIALIZED=1
  fi
  pyenv
'

#### Conda
_conda_init() {
    __conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
            . "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
        else
            export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:$PATH"
        fi
    fi
    unset __conda_setup
}

# Only initialize Conda if the user runs 'conda'
conda() {
    _conda_init
    unset -f conda
    command conda "$@"
}

#### LM Studio
# Add LM Studio to the path
export PATH="$PATH:$HOME/.lmstudio/bin"

# Add .local/bin -> for Rust
export PATH="$HOME/.local/bin:$PATH"

# atuin
. "$HOME/.atuin/bin/env"
eval "$(atuin init zsh)"
